# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vox/job_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vox/job_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vox import common_pb2 as vox_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vox/job_request.proto\x12\x03vox\x1a\x10vox/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n\x0fLocalFileSource\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x19\n\nHttpSource\x12\x0b\n\x03url\x18\x01 \x01(\t\"7\n\x08S3Source\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\"~\n\x06Source\x12*\n\nlocal_file\x18\x01 \x01(\x0b\x32\x14.vox.LocalFileSourceH\x00\x12\x1f\n\x04http\x18\x02 \x01(\x0b\x32\x0f.vox.HttpSourceH\x00\x12\x1b\n\x02s3\x18\x03 \x01(\x0b\x32\r.vox.S3SourceH\x00\x42\n\n\x08location\"P\n\x14TranscriptionOptions\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x12\n\nvad_filter\x18\x03 \x01(\x08\"g\n\x12\x44iarizationOptions\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x14\n\x0cnum_speakers\x18\x02 \x01(\r\x12\x14\n\x0cmin_speakers\x18\x03 \x01(\r\x12\x14\n\x0cmax_speakers\x18\x04 \x01(\r\"s\n\x11ProcessingOptions\x12\x30\n\rtranscription\x18\x01 \x01(\x0b\x32\x19.vox.TranscriptionOptions\x12,\n\x0b\x64iarization\x18\x02 \x01(\x0b\x32\x17.vox.DiarizationOptions\"\x8a\x02\n\nJobRequest\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x06source\x18\x05 \x01(\x0b\x32\x0b.vox.Source\x12%\n\x0coutput_types\x18\x06 \x03(\x0e\x32\x0f.vox.OutputType\x12\'\n\x07options\x18\x07 \x01(\x0b\x32\x16.vox.ProcessingOptions\x12\x1f\n\x08metadata\x18\x08 \x03(\x0b\x32\r.vox.KeyValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vox.job_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCALFILESOURCE']._serialized_start=81
  _globals['_LOCALFILESOURCE']._serialized_end=112
  _globals['_HTTPSOURCE']._serialized_start=114
  _globals['_HTTPSOURCE']._serialized_end=139
  _globals['_S3SOURCE']._serialized_start=141
  _globals['_S3SOURCE']._serialized_end=196
  _globals['_SOURCE']._serialized_start=198
  _globals['_SOURCE']._serialized_end=324
  _globals['_TRANSCRIPTIONOPTIONS']._serialized_start=326
  _globals['_TRANSCRIPTIONOPTIONS']._serialized_end=406
  _globals['_DIARIZATIONOPTIONS']._serialized_start=408
  _globals['_DIARIZATIONOPTIONS']._serialized_end=511
  _globals['_PROCESSINGOPTIONS']._serialized_start=513
  _globals['_PROCESSINGOPTIONS']._serialized_end=628
  _globals['_JOBREQUEST']._serialized_start=631
  _globals['_JOBREQUEST']._serialized_end=897
# @@protoc_insertion_point(module_scope)
