# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vox/job_status.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vox/job_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vox import common_pb2 as vox_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vox/job_status.proto\x12\x03vox\x1a\x10vox/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n\nWorkerInfo\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\"\xff\x01\n\x0eJobStatusEvent\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x03 \x01(\t\x12.\n\nemitted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1c\n\x05state\x18\x05 \x01(\x0e\x32\r.vox.JobState\x12\r\n\x05stage\x18\x06 \x01(\t\x12\x0f\n\x07\x61ttempt\x18\x07 \x01(\r\x12\x1f\n\x06worker\x18\x08 \x01(\x0b\x32\x0f.vox.WorkerInfo\x12\x1e\n\x07\x64\x65tails\x18\t \x03(\x0b\x32\r.vox.KeyValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vox.job_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERINFO']._serialized_start=80
  _globals['_WORKERINFO']._serialized_end=129
  _globals['_JOBSTATUSEVENT']._serialized_start=132
  _globals['_JOBSTATUSEVENT']._serialized_end=387
# @@protoc_insertion_point(module_scope)
